### ISSUE TITLE
Create options for interface and create channels

### ISSUE THREAD

**Issue by DJJo14** [grudolf/m3u2hts#5]
Create options for the network interface and whether you want to create the channels. 
Tvheadend 3.9 can scan for the channel information and map it.

a option for HTTP stream would be useful.

**Comment by grudolf** [comment]
Agree, the option to specify network interface is handy, you can now use -i eth1 or --iface=eth0.

Tvheadend 3.9+ output now uses same URI scheme in mux definition as provided in .m3u files:
    udp:@239.1.2.3:5000 -> udp://239.1.2.3:5000
    rtsp://host.domain/fbxtv_pub/stream?namespace=1&service=202&flavour=hd -> same
The scheme has to be one that tvh supports, ofc.

I'm not sure about omitting channels, can Tvheadend map muxes/services to epg without them?

**Comment by DJJo14** [comment]
I'm not sure about omitting channels, can Tvheadend map muxes/services to epg without them? 
Yes try adding a http stream.
And my iptv has EPG. Look in my Anneke script for more details

**Comment by grudolf** [comment]
Guess you're lucky - my IPTV provider has a mess no automatic matching solves. ;)

I've added -o service and -o channel options for 3.9 output, both disabled by default.
