### ISSUE TITLE
Need some help

### ISSUE THREAD

**Issue by gosch2912** [grudolf/m3u2hts#6]
Hello, I hope it is OK if I ask something here. 

I tried to run the m3u2hts.py script. I did it in a separate Folder, to look what’s happen.

I am not sure if I did all right. Maybe somebody can show me the right way:

`tobias@Spike-Linux:~/m3u2hts$ python m3u2hts.py mylist.m3u 
Traceback (most recent call last):
  File "m3u2hts.py", line 326, in <module>
    main()
  File "m3u2hts.py", line 318, in main
    readm3u(args[0], opt.removenum, opt.numbering, opt.codec)
  File "m3u2hts.py", line 52, in readm3u
    for line in instream.readlines():
  File "/usr/lib/python2.7/codecs.py", line 676, in readlines
    return self.reader.readlines(sizehint)
  File "/usr/lib/python2.7/codecs.py", line 585, in readlines
    data = self.read()
  File "/usr/lib/python2.7/codecs.py", line 474, in read
    newchars, decodedbytes = self.decode(data, self.errors)
  File "/usr/lib/python2.7/encodings/cp1250.py", line 15, in decode
    return codecs.charmap_decode(input,errors,decoding_table)`

Thank you for helping!

**Comment by grudolf** [comment]
The mylist.m3u file may be using a different encoding, try passing the correct one on the command line with the `-c` parameter , e.g.

```
m3u2hts.py -c utf-8 mylist.m3u ...
```

You can find the list of encodings at https://docs.python.org/2/library/codecs.html#standard-encodings

**Comment by gosch2912** [comment]
Thank you , that was exactly the problem. But it seems that this way is not supported for tv_headend 4.1.

So I will wait for Version 4.2, there you can play m3u playlists.....

**Comment by grudolf** [comment]
Yes, I've tested the direct m3u import in 4.1.1467 and it's working fine.
